kendaraan = ['B',"aerox",120,"hitam"]
kendaraan.append('16jt')
kendaraan.append(2)
kendaraan.insert(2,'yamaha')
kendaraan.insert(3,'maxy')

kodekendaraan = (kendaraan[0])
print("kode kendaraan:",kodekendaraan)
kodekendaraan = (kendaraan[1])
print("nama kendaraan:",kodekendaraan)
kodekendaraan = (kendaraan[2])
print("merk kendaraan:",kodekendaraan)
kodekendaraan = (kendaraan[3])
print("jenis kendaraan:",kodekendaraan)
kodekendaraan = (kendaraan[4])
print("cc kendaraan:",kodekendaraan)
kodekendaraan = (kendaraan[5])
print("warna kendaraan:",kodekendaraan)
kodekendaraan = (kendaraan[6])
print("harga kendaraan:",kodekendaraan)
kodekendaraan = (kendaraan[7])
print("jumlah ban:",kodekendaraan)